spring.application.name=demo
#puerto por defecto
server.port=8082
#base de datos
#JPA
#ThymeLeaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
#/templates/index.html 
#spring.thymeleaf.check-template-location=false













